pipeline {
    agent any
    stages {

        stage('check current directory') {
            steps {
                sh 'pwd'
            }
        }

        stage('check host') {
            steps {
                sh 'hostname'
            }
        }
        stage('check version python') {
            steps {
                sh 'python --version'
            }
        }
    }
}
